development:
  secret_key_base: 'XXX'
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token:  <%= ENV["TWILIO_AUTH_TOKEN"] %>

test:

production:
  secret_key_base: 'XXX'
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token:  <%= ENV["TWILIO_AUTH_TOKEN"] %>
